### ISSUE TITLE
Providers with bad API auth tokens can be added successfully

### ISSUE THREAD

**Issue by pavelzag** [dkorn/manageiq-ansible-module#44]
Tried to run the script with a random token and the action was successful.
Is there a plan to add token validation?

**Comment by dkorn** [comment]
yes, this PR: https://github.com/dkorn/manageiq-ansible-module/pull/21
It was pending for some time and I got back to it a few days ago. I'll revise it today.

**Comment by cben** [comment]
@dkorn I think this can be closed?

**Comment by dkorn** [comment]
@cben definitely, closing.
