### ISSUE TITLE
Failed to validate provider error

### ISSUE THREAD

**Issue by pavelzag** [dkorn/manageiq-ansible-module#50]
I am running an add_provider.yml and I am getting the following error:

# ansible-playbook add_provider.yml 
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Add Openshift Containers Provider to ManageIQ] ***************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to Validate provider authentication after addition. details: {'bearer': (u'Valid', u'Ok'), 'hawkular': (u'Error', u'<html>\\n  <head>\\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\\n  <style type=\"text/css\">\\n  /*!\\n   * Bootstrap v3.3.5 (http://getbootstrap.com)\\n   * Copyright 2011-2015 Twi...')}"}
	to retry, use: --limit @/var/lib/jenkins/workspace/cfme-5.7-ose-3.4-provider-test-dev/cfme_tests/utils/ansible_conf/add_provider.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

Here's my yaml:

[
  {
    "tasks": [
      {
        "register": "result",
        "manageiq_provider": {
          "provider_api_port": "8443",
          "hawkular_hostname": "something.redhat.com",
          "hawkular_port": "443",
          "miq_username": "admin",
          "miq_url": "https://x.x.x.x",
          "state": "present",
          "provider_api_hostname": "something.redhat.com",
          "provider_api_auth_token": "token",
          "name": "OSE",
          "metrics": "True",
          "miq_password": "password",
          "verify_ssl": "False",
          "provider_type": "openshift-origin"
        },
        "name": "Add Openshift Containers Provider to ManageIQ"
      },
      {
        "debug": "var=result"
      }
    ],
    "hosts": "localhost"
  }
]

**Comment by cben** [comment]
I'm seeing same error in UI (on fine) when I tried using same hostname for Hawkular as Default endpoint:
![manageiq containers providers 2](https://user-images.githubusercontent.com/273688/27290866-34b02d5c-5517-11e7-8237-ccd5292d2ae7.png)

The error is not helpful, but I don't think the ansible module can do anything about random HTTP responses from wrong hostname...
