### ISSUE TITLE
Adding provider to Euwe fails even if provider_verify_ssl is set to false

### ISSUE THREAD

**Issue by pavelzag** [dkorn/manageiq-ansible-module#61]
Attempting to run add_provider.yml with an Openshift provider and getting the following error:

"msg": "Failed to add provider. Error: APIException(\"Api::BadRequestError: Could not create the new provider - unknown attribute 'certificate_authority' for Endpoint.\",)"

The yml looks like this:

--- 
- 
  hosts: localhost
  tasks: 
    - 
      manageiq_provider: 
        hawkular_hostname: <hostname>
        hawkular_port: 443
        metrics: "True"
        miq_password: 
        miq_url: <url>
        miq_username: 
        miq_verify_ssl: "False"
        name: "CI OSE"
        provider_api_auth_token: <token>
        provider_api_hostname: <hostname>
        provider_api_port: 8443
        provider_type: openshift-origin
        state: present
      name: "Add Openshift Containers Provider to ManageIQ"
      register: result
    - 
      debug: var=result

More info here:
http://pastebin.test.redhat.com/466033

**Comment by cben** [comment]
Here you set `miq_verify_ssl` (insecure ansible to MIQ), for insecure MIQ
to provider you need `provider_verify_ssl: False`. (We may need better docs)

But that's not the error.  Which MIQ version?  Only 5.8 understands
certificate_authority field.  @dkorn we need backward compatibility.
Simplest idea is not sending certificate_authority unless provider_ca_path
specified.

**Comment by pavelzag** [comment]
Forgot to mention, this happens on 5.7.1.0 which may explain the problem

**Comment by cben** [comment]
@pavelzag can you try with current matter and confirm it's fixed?

**Comment by pavelzag** [comment]
I will check! Thanks

**Comment by pavelzag** [comment]
Hi Benni. Attempting to run against 5.8.0.7 I am getting the following:
```
                            "msg": "Failed to Validate provider authentication after addition. details: {'bearer': (u'Error', u'HTTP status code , SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed'), 'hawkular': (u'Error', u'SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed')}"
                        }
                    }, 

```
I have  "provider_verify_ssl": true.
What am I missing to make it work?

**Comment by cben** [comment]
Does this provider have a globally-trusted certificate (like from Let's Encrypt, VeriSign etc?)
Assuming not, you must also put the CA cert to trust in a file and point to it with `provider_ca_path`.
